version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_db
    image: postgres:13
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresgl/data
    ports:
      - 5432:5432
    volumes:
      -pgdata: /var/lib/postgresgl/data
    restart: always

volumes:
  pgdata: